### ISSUE TITLE
npm install memcpy fail

### ISSUE THREAD

**Issue by kaleidawave** [dcodeIO/node-memcpy#9]
Installing this package causes this error
```
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\_____\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
```

**Comment by dcodeIO** [comment]
The module is fairly old (and I'd say not needed anymore), so it hasn't been updated in a while and hence does not account for any potential recent changes. If you absolutely need it, I'd suggest creating a PR with a fix, otherwise I'd suggest using an alternative.
